### PR TITLE
feat(tls): add `deis tls`

### PR DESCRIPTION
**Pull request by bacongobbler**
supercedes #82, working around CI failures

adding @Joshua-Anderson's previous LGTM here

### CODE REVIEW

**Comment by bacongobbler** [comment]
Hmm, I thought this problem was fixed in https://github.com/deis/workflow-cli/pull/210...

> 3 errors occurred:
--> windows/amd64 error: exit status 2
Stderr: # github.com/deis/workflow-cli/cmd
cmd/ps.go:127: cannot range over procs (type api.PodType)

> --> linux/amd64 error: exit status 2
Stderr: # github.com/deis/workflow-cli/cmd
cmd/ps.go:127: cannot range over procs (type api.PodType)

> --> darwin/amd64 error: exit status 2
Stderr: # github.com/deis/workflow-cli/cmd
cmd/ps.go:127: cannot range over procs (type api.PodType)

**Comment by Joshua-Anderson** [comment]
@bacongobbler did you rebase this PR on master?

**Comment by bacongobbler** [comment]
Yep.

**Comment by bacongobbler** [comment]
Right now I'm looking into the issue by reproducing the tests locally, seeing why this would fail in CI

**Comment by bacongobbler** [comment]
re-rebasing seems to have fixed the issue. Looks like https://ci.deis.io/job/workflow-test-pr/6289 is going to fail though due to transient buildpack errors.

**Comment by bacongobbler** [comment]
commit passed Jenkins, need :eyes:

**Pull request merged**
