### PR TITLE
tests(ci): use jenkins for CI testing

### PR DESCRIPTION
**Pull request by Joshua-Anderson**

### CODE REVIEW

**Comment by vdice** [comment]
ok to test

**Comment by vdice** [comment]
ok to test

**Comment by Joshua-Anderson** [comment]
Jenkins is now working properly and this PR is ready to be reviewed. 💥

**Comment by Joshua-Anderson** [comment]
Just for the record, I didn't parallelize the windows/linux parts of this PR because has some annoying side affects. First, you can't use `stages

**Pull request merged**
