### PR TITLE
feat(*): Define composite types that are sortable

### PR DESCRIPTION
**Pull request by nathansamson**
Basically a port of https://github.com/deis/deis/pull/5072

Most important difference is in the Process listing, all others should be straight copies from V1

### CODE REVIEW

**Comment by Joshua-Anderson** [comment]
It looks like gofmt is failing on `api/keys.go` and `api/ps.go`. Also, it seems like a lot of the sorting tests didn't get ported, I only see `api/users_test.go`.

Thanks for porting this!

**Comment by nathansamson** [comment]
Sorry about that... Apparantly did not commit my last change and pushed the wrong one.

All should be good now

**Comment by Joshua-Anderson** [comment]
@nathansamson looks good. Thanks for your contribution!

**Comment by Joshua-Anderson** [comment]
@nathansamson Are you still interested in finishing up the sorting work in V2 by using these APIs to sort in workflow-cli? I'm happy to do it if you're busy or uninterested, I just wanted to make sure you weren't already working on it! This change is really useful because it can help with some of the e2e flakiness we've been seeing in CI lately.

**Comment by Joshua-Anderson** [comment]
As I somehow overlooked, the controller now sorts everything alphabetically by default, so sorting is no longer needed the CLI itself. Sorry about that 😊!

**Comment by nathansamson** [comment]
@Joshua-Anderson Hi, sorry bit overworked lately and have no direct incentive to complete this. Take over if you want to

Are you sure everything is sorted btw? Pretty sure pod names in ps are not sorted yet in V2 (although i did not verify this in any way)

**Comment by Joshua-Anderson** [comment]
>Are you sure everything is sorted btw? Pretty sure pod names in ps are not sorted yet in V2 (although i did not verify this in any way)

I haven't gone through and confirmed every resource. Thanks for the pointer on pod names, I'll check that.

Totally understand being busy! Thanks for all your work in this area. I'll investigate and make sure nothing was overlooked server side.

**Pull request merged**
